const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();
const initData=tg?.initData||'';const preview=!initData;const headers={'X-Telegram-Init-Data':initData,'Content-Type':'application/json'};
const money=n=>new Intl.NumberFormat('fa-IR').format(n||0)+' ریال';const size=n=>{if(!n)return '۰ GB';return new Intl.NumberFormat('fa-IR',{maximumFractionDigits:1}).format(n/1073741824)+' GB'};
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{...headers,...opt.headers}});if(!r.ok)throw new Error((await r.json()).detail||'خطای ارتباط');return r.json()}
async function load(){if(preview){org.textContent='نمایندگی نمونه';available.textContent=money(125000000);balance.textContent=money(100000000);credit.textContent=money(25000000);usage.textContent='۲.۸ TB';document.getElementById('children-count').textContent='۷';status.textContent='پیش‌نمایش';notice.textContent='حالت پیش‌نمایش وب‌اپ؛ داخل تلگرام اطلاعات واقعی نمایش داده می‌شود.';return}try{const d=await api('/v1/webapp/dashboard');org.textContent=d.organization.name;available.textContent=money(d.wallet.available_irr);balance.textContent=money(d.wallet.balance_irr);credit.textContent=money(d.wallet.credit_limit_irr);usage.textContent=size(d.usage.lifetime_bytes);document.getElementById('children-count').textContent=new Intl.NumberFormat('fa-IR').format(d.children_count)}catch(e){status.textContent='خطا';notice.textContent=e.message}}
async function children(){const rows=await api('/v1/webapp/children');document.getElementById('children-list').innerHTML=rows.length?rows.map(x=>`<div class="item"><div><b>${x.name}</b><p>${x.status}</p></div><span>${money(x.balance_irr+x.credit_limit_irr)}</span></div>`).join(''):'<div class="notice">هنوز زیرمجموعه‌ای ندارید.</div>'}
async function finance(){const rows=await api('/v1/webapp/transactions');document.getElementById('transactions').innerHTML=rows.length?rows.map(x=>`<div class="item"><div><b>${x.kind}</b><p>${new Date(x.created_at).toLocaleString('fa-IR')}</p></div><span>${x.side==='credit'?'+':'-'}${money(x.amount_irr)}</span></div>`).join(''):'<div class="notice">تراکنشی ثبت نشده است.</div>'}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.page).classList.add('active');if(b.dataset.page==='children')children();if(b.dataset.page==='finance')finance()});
const modal=document.getElementById('modal'),form=document.getElementById('modal-form'),fields=document.getElementById('modal-fields');let mode='';
function openModal(type){mode=type;modal.classList.add('open');document.getElementById('modal-title').textContent=type==='fund'?'درخواست افزایش اعتبار':'ساخت زیرمجموعه';fields.innerHTML=type==='fund'?'<label>مبلغ به ریال</label><input name="amount_irr" inputmode="numeric" required>':'<label>نام</label><input name="name" required><label>شناسه انگلیسی</label><input name="slug" required><label>قیمت هر گیگ</label><input name="price_per_gib_irr" inputmode="numeric" required><label>سقف اعتبار</label><input name="credit_limit_irr" inputmode="numeric" value="0">'}
fund.onclick=()=>openModal('fund');document.getElementById('new-child').onclick=()=>openModal('child');cancel.onclick=()=>modal.classList.remove('open');refresh.onclick=load;
form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));try{if(mode==='fund')await api('/v1/webapp/funding-requests',{method:'POST',body:JSON.stringify({amount_irr:+data.amount_irr})});else await api('/v1/webapp/children',{method:'POST',body:JSON.stringify({...data,price_per_gib_irr:+data.price_per_gib_irr,credit_limit_irr:+data.credit_limit_irr})});modal.classList.remove('open');tg?.HapticFeedback?.notificationOccurred('success');load()}catch(err){alert(err.message)}};load();
